services:
  app:
    image: jenrique138/app:staging
    container_name: rafarestaurante
    ports:
      - "8088:3000"
    environment:
      DB_HOST: mysql-infra
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
      DB_NAME: rafarestaurante
    networks:
      - rede_alunos
networks:
  rede_alunos:
    external: true
